############# English navigation ##############
# main menu      
[[main]]
name = "Services"
URL = "service"
weight = 3

[[main]]
name = "Tech Blog"
URL = "blog"
weight = 4

[[main]]
weight = 6
name = "About"
hasChildren = true

  [[main]]
  parent = "About"
  name = "About Us"
  URL = "about"

  [[main]]
  parent = "About"
  name = "Contacts"
  URL = "contact"

  # [[main]]
  # parent = "About"
  # name = "Pricing"
  # URL = "pricing"

  # [[main]]
  # parent = "About"
  # name = "Career"
  # URL = "career"
  
  [[main]]
  parent = "About"
  name = "Team"
  URL = "team"

  # [[main]]
  # parent = "About"
  # name = "FAQ"
  # URL = "faq"
  
  # [[main]]
  # parent = "About"
  # name = "Changelog"
  # URL = "changelog"

#Footer menu
# [[footer]]
# name = "Company History"
# URL = "about"

[[footer]]
name = "About us"
URL = "about"

[[footer]]
name = "Contact us"
URL = "contact"

[[footer]]
name = "Services"
URL = "service"

[[footer]]
name = "Privacy Policy"
URL = "privacy_policy"

#[[footer]]
#name = "Terms and Conditions"
#URL = "terms"