#################### default parameters ################################
# favicon
favicon = "images/favicon.ico"
# logo
logo = "images/logo.png"
# OpenGraph / Twitter Card metadata
description = "CMPSoares Lda. is an IT Consulting Company specialized in assisting Company with their Digital and Automation needs and helping them to build a strong Digital Presence."
author = "CMPSoares, Lda."
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact info
# address = "9567 Turner Trace Apt. 466 North Willie, BC C3G8A4"
mobile = "+44 20 8638 8170"
whatsapp = "442086388170"
whatsapp_label = "+44 20 8638 8170"
email = "contact@cmpsoares.com"
# contact form action
contact_form_action = "https://formspree.io/f/mrgrnyzq" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-216173935-1"
# main sections
mainSections = ["blog"]
# search
search = true
# custom script on header
custom_script= ""


# Preloader
[preloader]
enable = true
preloader = "images/Horizontal BLUE ICON.svg" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Contact Us"
link = "/contact"

# Subscription
[subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://cmpsoares.us4.list-manage.com/subscribe/post?u=a37f9f4e15985d7754bad97ba&amp;id=284d8c24ca" # replace this url with yours
mailchimp_form_name = "b_a37f9f4e15985d7754bad97ba_284d8c24ca" # replace this code with yours

# Google Services
# Google Adsense
[google_adsense]
enable = false # tagmanager is used
client = "ca-pub-9080200840721283"
inArticleSlot = "9080200840721283"

# google maps
[gmap]
enable = true
gmap_api = "AIzaSyCYvuegtMCWiaZU4xIyZeFbXUVw7woGH6E"
gmap_latitude = "38.769248259734226"
gmap_longitude = "-9.094876311500547"
gmap_marker = "images/marker.png"
gmap_marker_label = "CMPSoares, Lda."
gmap_zoom = 10

# google tag manager
[google_tagmanager]
enable = true
tagmanager_id = "GTM-WHLHKSH"

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use. For more details please check our [cookie policy](https://cmpsoares.com/cookie_policy.html)"
button = "I Accept"

[tidio_chatbot]
enable = true
id = "7ddfxeybyiti3uffdq8ewy4onogssfzd"

[termly]
enable = true
data_website_uuid="80bf8d48-6a62-46f0-b136-a7c488fe91c3"

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.facebook.com/cmpsoares"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://twitter.com/cmpsoares"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.instagram.com/cmpsoares.lda/"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/cmpsoares"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin-in" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/company/cmpsoares"

[[social]]
title = "medium"
icon = "fab fa-medium" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://medium.com/cmpsoares"

[[social]]
title = "youtube"
icon = "fab fa-youtube" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.youtube.com/channel/UCIfNE0xB-uiR1Rc-OIXzTlw"
